name: infoprofile_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^3.5.0
  animated_text_kit: ^4.2.2


  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.3
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.7
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0

  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^2.6.0
  provider: ^6.0.5

  shared_preferences: ^2.2.2

  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Empty.png
  color_dark: "#000000"
  image_dark: assets/images/Empty.png
  android_12:
    icon_background_color: "#FFFFFF"
    image: assets/images/Empty.png
    icon_background_color_dark: "#000000"
    image_dark: assets/images/Empty.png
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/svg/
    - .env
